apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.EngineConfig.Name}}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.EngineConfig.Name}}
                port:
                  number: 9003